org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#Project
projectName=RebindNarrator
buildVer=1.2.2
neoforgeVer=21.10.64
mcVer=1.21.10
jarMCVer=1.21.9+
mcVerRange=[1.21.9, 1.22)
neoVerRange=[21.9, 22)
author=Ocraftyone
license=Custom - See Curseforge
projectDescription=Allows you to rebind the narrator toggle keybind

#Advanced Features
useMixins=true
useAT=false
