org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#Project
projectName=RebindNarrator
buildVer=1.2.2
neoforgeVer=21.8.52
mcVer=1.21.8
jarMCVer=1.21-1.21.8
mcVerRange=[1.21,1.21.8]
neoVerRange=[21.0, 21.8]
author=Ocraftyone
license=Custom - See Curseforge
projectDescription=Allows you to rebind the narrator toggle keybind

#Mappings
parchmentVer=2025.09.14

#Advanced Features
useMixins=true
useAT=false
